CREATE TABLE IF NOT EXISTS CLIENT (
	ID UUID DEFAULT uuid_generate_v4 (),
	JVERSION INT,
	FULL_NAME VARCHAR(50) NOT NULL,
	BIRTH_DATE DATE,
	CPF VARCHAR(14) NOT NULL,
	RG VARCHAR(13),
	DDD VARCHAR(2) NOT NULL,
	PHONE_NUMBER VARCHAR(10) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	SEX VARCHAR(10),
	ACTIVE BOOLEAN NOT NULL,
	DELETED BOOLEAN NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP,
	DELETED_AT TIMESTAMP,
	PRIMARY KEY(ID)
);