CREATE TABLE IF NOT EXISTS ADDRESS (
	ID UUID DEFAULT uuid_generate_v4 (),
	JVERSION INT,
	STREET VARCHAR(50) NOT NULL,
	NUMBER INT,
	COMPLEMENT VARCHAR(20) NOT NULL,
	NEIGBORHOOD VARCHAR(20),
	ZIP_CODE VARCHAR(9) NOT NULL,
	REFERENCE VARCHAR(20) NOT NULL,
	CITY VARCHAR(30) NOT NULL,
	STATE VARCHAR(10),
	COUNTRY VARCHAR(10),
	ACTIVE BOOLEAN NOT NULL,
    DELETED BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    UPDATED_AT TIMESTAMP(6),
    DELETED_AT TIMESTAMP(6),
	PRIMARY KEY(ID)
);